### ISSUE TITLE
Implement collision avoidance in "go to" action

### ISSUE THREAD

**Issue by matheusportela** [unball/ieee-very-small#36]
Using forces to repel other robots and walls at the same time to attract to the desired position is an interesting way to implement the `goTo` action.

**Comment by matheusportela** [comment]
Interesting reference: http://hmi.ewi.utwente.nl/robotsoccernieuw/documents/thesis_joost_vd_linden.pdf

**Comment by imota** [comment]
Isnt this issue obsolete? Because there are new ones about force fields. Shouldn't we close this one? Or are they really different issues?

**Comment by matheusportela** [comment]
Closed since potential fields should implement collision avoidance anyway.
