### ISSUE TITLE
Test all the basic potential field classes to ensure they are working correctly

### ISSUE THREAD

**Issue by imota** [unball/ieee-very-small#54]
Namely: AttractiveField, RepulsiveField, PerpendicularField, TangentialField, ParallelField, and SelectiveField

**Comment by izabellagomes** [comment]
Repulsive and Atractive potential fields tested, and fixed.
Tangential and Selective fields are in progress.

**Comment by matheusportela** [comment]
Were all fields tested? Should this issue be closed?

**Comment by imota** [comment]
Attractive and Repulsive are good to go.

Perpendicular and parallel need a final revision, but should be ok (we dont remember whether we tested those or not, but I think they are fine).

Tangential needs to be implemented. Actually, it is already implemented into Selective field. 

Selective field implements the attractive field (again) and the tangential field so it needs an urgent refactor
