### ISSUE TITLE
Add 2 new trackbars for SMax and VMax

### ISSUE THREAD

**Issue by vieiramanoel** [unball/ieee-very-small#69]

**Comment by matheusportela** [comment]
Is this issue still open?

**Comment by vieiramanoel** [comment]
No.

Em 16:07, Sáb, Jan 9, 2016, Matheus Vieira Portela <notifications@github.com>
escreveu:

> Is this issue still open?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/unball/ieee-very-small/issues/69#issuecomment-170270677>
> .
>
-- 
Vieira Neto
Graduando de Engenharia Mecatrônica - UnB

**Comment by matheusportela** [comment]
Closing issue since @vieiramanoel assured it isn't open anymore.
